<SplashScreen>:
    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: 0.08, 0.08, 0.08, 1
        adaptive_height: False
        spacing: "20dp"
        padding: "40dp"

        MDLabel:
            text: "AlertX2"
            halign: "center"
            font_style: "H3"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            bold: True

        MDLabel:
            text: "Personal Safety & Rapid Emergency Response"
            halign: "center"
            theme_text_color: "Secondary"
